spring:
  application:
    name: ai-agents-rag-mcp-bedrock
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  ai:
    model:
      embedding: bedrock-cohere
    bedrock:
      aws:
        region: ${AWS_REGION:us-east-1}
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
        session-token: ${AWS_SESSION_TOKEN}
      converse:
        chat:
          options:
            model: amazon.nova-pro-v1:0
    vectorstore:
      pgvector:
        table-name: bedrock_vector_store
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
    mcp:
      client:
        enabled: true
        toolcallback:
          enabled: true
        sse:
          connections:
            server1:
              url: http://mcp-server:8081

# Vector Store Initialization Control
app:
  vectorstore:
    initialize: ${VECTORSTORE_INITIALIZE:false}

# Logging
logging:
  level:
    org:
      springframework:
        ai: DEBUG
        jdbc: DEBUG
    io:
      modelcontextprotocol: TRACE
